BoardGameApp/Models/BoardGameModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BoardGameApp.Models
{
    public class BoardGameModel
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; } 
        public string ImageURL { get; set; }

        [ForeignKey("PublisherId")]
        public int PublisherId { get; set; }

        public virtual PublisherModel? Publisher { get; set; }

        [NotMapped]
        public string? NewPublisher { get; set; }

    }
}

BoardGameApp/Models/ErrorViewModel.cs
namespace BoardGameApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BoardGameApp/Models/PublisherModel.cs
using System.ComponentModel.DataAnnotations;

namespace BoardGameApp.Models
{
    public class PublisherModel
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }

        //stores all the Board games associated with the Id property.
        public virtual IEnumerable<BoardGameModel>? BoardGame { get; set; }
    }
}

BoardGameApp/Controllers/BoardGameController.cs
using BoardGameApp.Data;
using BoardGameApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BoardGameApp.Controllers
{
    public class BoardGameController : Controller
    {
        private readonly GameContext _context;
        public BoardGameController(GameContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            return View(_context.BoardGames.Include(p => p.Publisher).ToList());
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(BoardGameModel boardGame)
        {
            if (ModelState.IsValid)
            {

                boardGame.PublisherId = GetPublisher(boardGame.NewPublisher);
                _context.BoardGames.Add(boardGame);
                _context.SaveChanges();
                return RedirectToAction("Index");


            }
            return View(boardGame);

        }

        public IActionResult Edit(int id)
        {
            var game = _context.BoardGames.Include(g => g.Publisher).FirstOrDefault(g => g.Id ==id);
            return View(game);
        }
        [HttpPost]
        public ActionResult Edit(int id, BoardGameModel game)
        {
            if (ModelState.IsValid)
            {
                game.PublisherId = GetPublisher(game.NewPublisher);
                _context.Update(game);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(game);
        }

        public IActionResult Details(int id)
        {
            var game = _context.BoardGames.Where(g => g.Id == id).Include(b => b.Publisher).FirstOrDefault();
            return View(game);
        }

        public IActionResult Delete(int id)
        {
            var game = _context.BoardGames.FirstOrDefault(g => g.Id == id);
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }
        [HttpPost]
        public IActionResult Delete(int? id)
        {
            var game = _context.BoardGames.Find(id);
            _context.BoardGames.Remove(game);
            _context.SaveChanges();
            return RedirectToAction("index");
        }


        public int GetPublisher(string publisher)
        {
            PublisherModel? pub = null;
            pub = _context.Publishers.Where(p => p.Name.ToLower() == publisher.ToLower()).FirstOrDefault();
            if(pub == null)
            {
                pub = new PublisherModel { Name = publisher };
                _context.Publishers.Add(pub);
                _context.SaveChanges();
            }
            return pub.Id;
        }

    }
}

BoardGameApp/Controllers/HomeController.cs
using BoardGameApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BoardGameApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BoardGameApp/Controllers/PublisherController.cs
using BoardGameApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BoardGameApp.Controllers
{
    public class PublisherController : Controller
    {
        private readonly GameContext _context;
        public PublisherController(GameContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var publishers = _context.Publishers.Include(b => b.BoardGame).ToList();
            return View(publishers);
        }

        public IActionResult Details(int id)
        {
            var publisher
                = _context.Publishers.Where(p => p.Id == id).Include(b => b.BoardGame).FirstOrDefault();
            return View(publisher);
        }

    }
}

BoardGameApp/Views/BoardGame/Create.cshtml
@model BoardGameApp.Models.BoardGameModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BoardGameModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publisher" class="control-label"></label>
                <input asp-for="NewPublisher" class="form-control" />
                <span asp-validation-for="NewPublisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BoardGameApp/Views/BoardGame/Delete.cshtml
@model BoardGameApp.Models.BoardGameModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BoardGameModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageURL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BoardGameApp/Views/BoardGame/Details.cshtml
@model BoardGameApp.Models.BoardGameModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>@Model.Name</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            <img class="rounded-circle" src="@Model.ImageURL" alt="@Model.Name"
                 style="max-width: 150px" />
            </dt>
       
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BoardGameApp/Views/BoardGame/Edit.cshtml
@model BoardGameApp.Models.BoardGameModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BoardGameModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publisher" class="control-label"></label>
                <input asp-for="NewPublisher" value="@Model.Publisher.Name"class="form-control"></input>
                <span asp-validation-for="NewPublisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BoardGameApp/Views/BoardGame/Index.cshtml
@model IEnumerable<BoardGameApp.Models.BoardGameModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ImageURL)
            </th>
            <th>
                
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
               @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Publisher)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
               <img class="rounded-circle" src="@item.ImageURL" alt="@item.Name"
                 style="max-width: 70px" />
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Publisher.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

BoardGameApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BoardGameApp/Views/Publisher/Details.cshtml
@model PublisherModel



<table class="table">

    <tbody>



@foreach(var item in Model.BoardGame)
{
    <tr>
        <td>

                @item.Name
        </td>

        <td class="align-middle">
                    <img class="rounded-circle" src="game.imageURL" alt="@item.Name" 
                    style="max-width: 150px">
        </td>
        
    </tr>



}




    </tbody>

</table>

BoardGameApp/Views/Publisher/Index.cshtml
@model IEnumerable<PublisherModel>

    <h1>Publishers Index Page</h1>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Publishers
                </th>
            </tr>
        </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Games</a>
                </td>
            </tr>
         
        }
    </tbody>
</table>

@*<td>
    @Html.DisplayFor(modelItem => item.Name)
</td>
<td>
    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
</td>*@

BoardGameApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BoardGameApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BoardGameApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BoardGameApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publisher" asp-action="Index">Publisher</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BoardGame" asp-action="Index">Board Game</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BoardGameApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>